theme: minima
title: Contract Templates to merge Contractors and employees 
author: Renato Pasquini
description: Blockchain contracts to clue the job offers with the candidates, avoiding middle consulting.
